language: minimal

services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/$IMAGE .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push $DOCKER_USERNAME/$IMAGE
  on:
    branch: master
  skip_cleanup: true
